apiVersion: v1
kind: Pod
metadata:
  labels:
    app: busybox
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox:1
    resources: {}
    command: ['sh', '-c', "while true; do echo 'busybox is running'; sleep 100;done"]