version: 2.1

jobs:
  docker-build:
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
     - checkout # checkout source code from git
     - setup_remote_docker
     - run:
          name: build images and tag docker hub
          command: |
            # build image
            docker-compose -f docker-compose-build.yaml build --parallel
            
            # tag image
            docker tag udagram-api-feed:v1 $DOCKERHUB_USERNAME/udagram-api-feed:v1
            docker tag udagram-api-user:v1 $DOCKERHUB_USERNAME/udagram-api-user:v1
            docker tag udagram-frontend:v1 $DOCKERHUB_USERNAME/udagram-frontend:v1
            docker tag udagram-reverseproxy:v1 $DOCKERHUB_USERNAME/udagram-reverseproxy:v1
            
            # list image
            docker images
            
            # login
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

            # push to DockerHub
            docker push $DOCKERHUB_USERNAME/udagram-api-feed:v1
            docker push $DOCKERHUB_USERNAME/udagram-api-user:v1
            docker push $DOCKERHUB_USERNAME/udagram-frontend:v1
            docker push $DOCKERHUB_USERNAME/udagram-reverseproxy:v1
          
workflows:
  buildOnMaster:
    jobs:
      - docker-build:
          filters:
            branches:
              only: [master]
